### PR TITLE
fixed date error for jekyll compilation of pages on github.io

### PR DESCRIPTION
**Pull request by tibbben**
With this pull request it should work now (date format error in the readme.md), but note, I also had to make sure the settings for the "pages" deployment in the GitHub repo must be set to the gh-pages branch. With these two changes it works for me.

best
tim

### CODE REVIEW

**Comment by gabrielodom** [comment]
Ok, so I tried to implement the date fix directly, but it didn't work. After I fix the date, do I change the shell code to `mkdocs gh-deploy --remote-branch master` so that the website builds?

Unrelated note: this pull request deletes basically all the .html files. Why is that a good thing?

**Comment by tibbben** [comment]
shell code should remain the same and deploy from your local shell, it will push to the gh-pages branch on the repo. Just make sure the repo settings for the gh-pages point to the gh-pages branch

**Comment by gabrielodom** [comment]
Shell code remains the same. That I understand. I don't understand this: "Just make sure the repo settings for the gh-pages point to the gh-pages branch"

**Comment by tibbben** [comment]
we don't need the html code in the site folder on the master branch, only in the gh-pages branch. Note that if you deploy from the command line using medics gh-deploy, it pushes all html pages to the gh-pages branch automatically. This is following best practices from the medics docs here: https://www.mkdocs.org/user-guide/configuration/

**Comment by tibbben** [comment]
silly auto correct

**Comment by tibbben** [comment]
sent meeting invite ...

**Pull request merged**
